package com.digitalchocolate.socailbetting.exception;

/**
 * this exception is generated by internal system not an exception due to client data error.
 * @author hliang
 *
 */
public class SocialBettingInternalException extends RuntimeException{
	
	private static final long serialVersionUID = -5843141707875820838L;


	public SocialBettingInternalException() {
	        super();
    }

    public SocialBettingInternalException(String message) {
        super(message);
    }

   
    public SocialBettingInternalException(String message, Throwable cause) {
        super(message, cause);
    }

  
    public SocialBettingInternalException(Throwable cause) {
        super(cause);
    }

   
    protected SocialBettingInternalException(String message, Throwable cause,
                               boolean enableSuppression,
                               boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }
}
